Name="charan"
#variable=value
# variable is the leftsidee one and value is right side one 
# to assign a value we use a variable and it has rules like 
# it should not begin with numders EX: 23name
# special characters should not be taken except for _
# the variable name should not be a keyword
# it is a case sensitive EX: Age is not equal to age

data types 
integer type:
num=10
float type:
num=10.0
double type:
num=10.0